### ISSUE TITLE
Doesn't start / missing "add_args" in common

### ISSUE THREAD

**Issue by patrickpracht** [sharky5102/fbmatrix#4]
Hi,

I'm trying to get this running.

I cloned the repo, executed the steps mentioned in readme and got this:
```
pi@raspberrypi:~/fbm $ ./fbmtest.py gradient
Traceback (most recent call last):
  File "/home/pi/fbm/fbmtest.py", line 94, in <module>
    common.add_args(parser)
AttributeError: module 'common' has no attribute 'add_args'
```

```
pi@raspberrypi:~/fbm $ ./fbmplay.py demo.mp4
Traceback (most recent call last):
  File "/home/pi/fbm/./fbmplay.py", line 54, in <module>
    common.add_args(parser)
AttributeError: module 'common' has no attribute 'add_args'
```

If I comment out `common.add_args(parser)` it complains about missing `common.renderer_from_args(args)` instead.

I've tried going back to commit [47d802b43c2c8db61b2c71d36645b8ea01351571](https://github.com/sharky5102/fbmatrix/commit/47d802b43c2c8db61b2c71d36645b8ea01351571) where at least `fbmtest` (no .py extension) is starting, but it doesn't output anything.

I've verified my setup by using the original hzeller-lib with the adafruit-hat mode (it displays the demos very nicely) and `raspi-gpio get` indicates that the dpi24 overlay is loaded, because it shows the gpios on bank0 in alt2 mode.

What am I missing here?

**Comment by sharky5102** [comment]
Fixed missing common
